[Interface]
PrivateKey = 2NHZoVhwiHZPYZl8bWpebMNh3CzhhtHTsEzh9uGbg18=
Address = 10.222.0.1/24
ListenPort = 51820
# Ограничиваем исходящий трафик, чтобы не превышать лимит TURN-релея
PostUp = tc qdisc add dev %i root tbf rate 1.8mbit burst 32kbit latency 50ms
PostDown = tc qdisc del dev %i root 2>/dev/null || true

[Peer]
# Local Client
PublicKey = J3ew2SGPYN4hLN0hFs8Idh3hlXOEpiBjbHF5bIXSNiw=
AllowedIPs = 10.222.0.2/32
